### ISSUE TITLE
`kmir parse` fail in Docker container.

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics#150]
Please refer to this issue https://github.com/runtimeverification/pyk/issues/456
and the evaluation comments fron w3f: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rv-kmir_2_dsm-w3f.md

**Comment by geo2a** [comment]
The root of the issue is that the K definitions are not built and hence the directories do not exist. I've adjusted the `build` Makefile target to perform `poetry install` (see https://github.com/runtimeverification/mir-semantics/pull/151). This will ensure that `kbuild` is installed to build the K definitions. With this change, the suggested sequence of commands to run the wanted parsing example is from scratch in Docker is:

```
git clone --recurse-submodules git@github.com:runtimeverification/mir-semantics.git
cd mir-semantics
sudo docker build . --build-arg K_COMMIT=$(cat ./deps/k_release) --tag mir-semantics:$(cat ./deps/k_release)
sudo docker run --name mir-semantics --rm -it -u user --workdir /home/user mir-semantics:$(cat ./deps/k_release)
cd kmir
make build
poetry shell # to make kmir and kbuild availible without having to type "poetry run"
kmir parse --definition-dir $(kbuild which llvm) src/tests/integration/test-data/handwritten-mir/execution/assert-true.mir
```

**Comment by yanliu18** [comment]
Thank you @geo2a, the fix is tested working on my machine with docker.
