### ISSUE TITLE
BUG: `make handwritten-prove-fail` not updating `.tsv` file

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#309]
### Problem
`make handwritten-prove-fail` is correctly running the proofs and reporting the results on the command line, however the `handwritten-prove-fail.tsv` is not updated with the failing proofs.

### Solution
Investigate `test_prove.py` to resolve the issue

**Comment by yanliu18** [comment]
There could be two reasons:
1. It might not be able to right to the existing file, you might want to delete the old file and regenerate.
2. If the particular error code is not updated, it is because of the over-simplication in the following line: https://github.com/runtimeverification/mir-semantics/blob/4c3b5aa6a00204c66cf8979a59425ab9fd0bb819/kmir/src/tests/integration/test_prove.py#L59
